# Generated by Django 6.1 on 2026-10-09 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], default='M', max_length=2)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('EA', 'Em andamento'), ('C', 'Concluída')], default='P', max_length=2)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='tarefas.categoria')),
            ],
        ),
    ]
